name: Playwright Tests
on:
  workflow_dispatch:
jobs:
  test:
#    timeout-minutes: 60 # remove job timeout to avoid premature cancellation - 5 devices x 1 runners (e.g, Running 165 tests using 1 worker)
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Install dependencies
      run: npm ci
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Run Playwright tests (FF only)
      run: npx playwright test --project=firefox
      env:
        NETLIFY_PASSWORD: ${{ secrets.NETLIFY_PASSWORD }}
        TEST_USER_EMAIL: ${{ secrets.TEST_USER_EMAIL }}
        TEST_USER_PASSWORD: ${{ secrets.TEST_USER_PASSWORD }}
    - name: Upload Playwright report
      uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
